const Keyboard = {
    content: {
      mainContainer: null,
      displayWindow: null,
      discriptionWindow: null,
      keyboardWindow: null,
      keyboardWrapper: null,
      keys: [],
    },
  
    data: {
      upperCase: false,
      lang: 'en',
      text: '',
    },
  
    eventHandlers: {
      oninput: null,
      onclose: null,
    },
  
    lang: {
      en: [
        [
          ['1', 'Digit1'],
          ['2', 'Digit2'],
          ['3', 'Digit3'],
          ['4', 'Digit4'],
          ['5', 'Digit5'],
          ['6', 'Digit6'],
          ['7', 'Digit7'],
          ['8', 'Digit8'],
          ['9', 'Digit9'],
          ['0', 'Digit0'],
          ['-', 'Minus'],
          ['=', 'Equal'],
          ['backspace', 'Backspace'],
        ],
        [
          ['tab', 'Tab'],
          ['q', 'KeyQ'],
          ['w', 'KeyW'],
          ['e', 'KeyE'],
          ['r', 'KeyR'],
          ['t', 'KeyT'],
          ['y', 'KeyY'],
          ['u', 'KeyU'],
          ['i', 'KeyI'],
          ['o', 'KeyO'],
          ['p', 'KeyP'],
          ['[', 'BracketLeft'],
          [']', 'BracketRight'],
          ['del', 'Delete'],
        ],
        [
          ['caps', 'CapsLock'],
          ['a', 'KeyA'],
          ['s', 'KeyS'],
          ['d', 'KeyD'],
          ['f', 'KeyF'],
          ['g', 'KeyG'],
          ['h', 'KeyH'],
          ['j', 'KeyJ'],
          ['k', 'KeyK'],
          ['l', 'KeyL'],
          [';', 'Semicolon'],
          ['"', 'Quote'],
          ['\\', 'Backslash'],
          ['enter', 'Enter'],
        ],
        [
          ['shift', 'ShiftLeft'],
          ['z', 'KeyZ'],
          ['x', 'KeyX'],
          ['c', 'KeyC'],
          ['v', 'KeyV'],
          ['b', 'KeyB'],
          ['n', 'KeyN'],
          ['m', 'KeyM'],
          [',', 'Comma'],
          ['.', 'Period'],
          ['↑', 'ArrowUp'],
          ['/', 'Slash'],
          ['shift', 'ShiftRight'],
        ],
        [
          ['ctrl', 'ControlLeft'],
          ['win', 'MetaLeft'],
          ['alt', 'AltLeft'],
          ['space', 'Space'],
          ['alt', 'AltRight'],
          ['←', 'ArrowLeft'],
          ['↓', 'ArrowDown'],
          ['→', 'ArrowRight'],
          ['ctrl', 'ControlRight'],
        ],
      ],
  
      rus: [
        [
          ['1', 'Digit1'],
          ['2', 'Digit2'],
          ['3', 'Digit3'],
          ['4', 'Digit4'],
          ['5', 'Digit5'],
          ['6', 'Digit6'],
          ['7', 'Digit7'],
          ['8', 'Digit8'],
          ['9', 'Digit9'],
          ['0', 'Digit0'],
          ['-', 'Minus'],
          ['=', 'Equal'],
          ['backspace', 'Backspace'],
        ],
        [
          ['tab', 'Tab'],
          ['й', 'KeyQ'],
          ['ц', 'KeyW'],
          ['у', 'KeyE'],
          ['к', 'KeyR'],
          ['е', 'KeyT'],
          ['н', 'KeyY'],
          ['г', 'KeyU'],
          ['ш', 'KeyI'],
          ['щ', 'KeyO'],
          ['з', 'KeyP'],
          ['х', 'BracketLeft'],
          ['ъ', 'BracketRight'],
          ['del', 'Delete'],
        ],
        [
          ['caps', 'CapsLock'],
          ['ф', 'KeyA'],
          ['ы', 'KeyS'],
          ['в', 'KeyD'],
          ['а', 'KeyF'],
          ['п', 'KeyG'],
          ['р', 'KeyH'],
          ['о', 'KeyJ'],
          ['л', 'KeyK'],
          ['д', 'KeyL'],
          ['ж', 'Semicolon'],
          ['э', 'Quote'],
          ['ё', 'Backslash'],
          ['enter', 'Enter'],
        ],
  
        [
          ['shift', 'ShiftLeft'],
          ['я', 'KeyZ'],
          ['ч', 'KeyX'],
          ['с', 'KeyC'],
          ['м', 'KeyV'],
          ['и', 'KeyB'],
          ['т', 'KeyN'],
          ['ь', 'KeyM'],
          ['б', 'Comma'],
          ['ю', 'Period'],
          ['↑', 'ArrowUp'],
          ['/', 'Slash'],
          ['shift', 'ShiftRight'],
        ],
        [
          ['ctrl', 'ControlLeft'],
          ['win', 'MetaLeft'],
          ['alt', 'AltLeft'],
          ['space', 'Space'],
          ['alt', 'AltRight'],
          ['←', 'ArrowLeft'],
          ['↓', 'ArrowDown'],
          ['→', 'ArrowRight'],
          ['ctrl', 'ControlRight'],
        ],
      ],
    },
}

window.onload = function () {
    console.log('Hello world!');
};